### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by b11r1m** [Lexxrt/FireFly#1]
$python FireFly.py +919800000000

  _____ _          _____ _       
 |  ___(_)_ __ ___|  ___| |_   _ 
 | |_  | | '__/ _ \ |_  | | | | |
 |  _| | | | |  __/  _| | | |_| |
 |_|   |_|_|  \___|_|   |_|\__, |
                           |___/ 
	Author: Lexxrt
	Github: https://github.com/Lexxrt             
	
Traceback (most recent call last):
  File "FireFly.py", line 84, in <module>
    main()
  File "FireFly.py", line 31, in main
    country_code = obj['country_code']
KeyError: 'country_code'

**Comment by b11r1m** [comment]
![phone](https://user-images.githubusercontent.com/56333884/106142382-85589e00-6199-11eb-904d-4df64fcc6265.png)

**Comment by Lexxrt** [comment]
Did you run it in python 3?

**Comment by Lexxrt** [comment]
Solved! Please clone the repo again in order for it to work

NOTE: This tool works using an API from https://numverify.com/. You can get ur own if your u want :)

**Comment by Blipee** [comment]
Hello! Do we need to get our own API and if so, I plug it into to the config file? No issue getting my own, just pretty new to Python so appreciate any guidance. Thank you :)
